language: php

php:
  - '7.3.8'

env:
  - REDIS_HOST=0.0.0.0 REDIS_PORT=6379

services:
  - docker

before_install:
  - docker run -d -p 0.0.0.0:6379:6379 --name redis redis:alpine
  - echo "extension=redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

before_script:
  - composer install

script:
  - make test