language: php

php:
  - '7.4'
  - '8.0'
  - '8.1'

env:
  - REDIS_HOST=0.0.0.0 REDIS_PORT=6379 XDEBUG_MODE=coverage

services:
  - docker

before_install:
  - docker run -d -p 0.0.0.0:6379:6379 --name redis redis:alpine
  - echo "extension=redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo '' | pecl install swoole-4.8.12
  - echo "extension=swoole.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

before_script:
  - composer install

script:
  - ./vendor/bin/phpunit --testdox tests